# Generated by Django 3.2.25 on 2024-05-08 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IHAModule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('iha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hires', to='IHAModule.iha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
