# Generated by Django 3.2.25 on 2024-05-08 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IHAModule', '0001_initial'),
        ('HiringModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='iha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iha', to='IHAModule.iha'),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
