# Generated by Django 5.0.6 on 2024-05-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiringModule', '0003_alter_hiring_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiring',
            options={'permissions': [('user_list_hiring', 'Can user list hirings'), ('user_delete', 'Can user delete'), ('user_update', 'Can user update'), ('admin_list_hiring', 'Can admin list hirings'), ('admin_delete', 'Can admin delete'), ('admin_update', 'Can admin update')]},
        ),
    ]
